### ISSUE TITLE
Non Integer Scores

### ISSUE THREAD

**Issue by CrunchNCrisp** [RamenReviewers/ramenreviewers.github.io#2]
As A Reviewer, I want to be able to give non-integer Reviews and have the score board display them properly.

- [x] Support Non-Integer Reviews in Backend
- [x] Display Non-Integer Reviews in Frontend
- [x] Hide negative values in frontend

**Comment by IcECreAm777** [comment]
Should be finished. Can be closed after Pull request for the "floating-number-review" was approved and merged

**Comment by CrunchNCrisp** [comment]
implemented with https://github.com/RamenReviewers/ramenreviewers.github.io/pull/13
